// eeprom.c Code generated by MCC for PIC18F26Q10 
// and then placed into this file by PJ.
// 2024-07-13 Adapted to PIC18F46Q71 using description in data sheet.

#include <xc.h>
#include <stdint.h>

void DATAEE_WriteByte(uint16_t bAdd, uint8_t bData)
// See PIC18F46Q71 data sheet, section 10.4.2, Example 10-10
{
    uint8_t GIEBitValue = INTCON0bits.GIE;
    
    // Set NVMADR with the target word address: 0x380000 - 0x3800FF
    // See data sheet Figure 9-1 Program and Data Memory Map
    NVMADRU = 0x38;
    NVMADRH = (uint8_t)((bAdd & 0xFF00) >> 8);
    NVMADRL = (uint8_t)(bAdd & 0x00FF);

    // Load NVMDATL with desired byte
    NVMDATL = (uint8_t)(bData & 0xFF);
    
    //Disable interrupts
    INTCON0bits.GIE = 0;

    //Perform the unlock sequence
    NVMLOCK = 0x55;
    NVMLOCK = 0xAA;

    //Start DATAEE write and wait for the operation to complete
    NVMCON1bits.CMD = 0b011;
    NVMCON0bits.GO = 1;
    while (NVMCON0bits.GO) /* wait */ ;
    //
    // Restore all the interrupts
    INTCON0bits.GIE = GIEBitValue;
    //
    // Disable NVM write command.
    NVMCON1bits.CMD = 0b000;
}

uint8_t DATAEE_ReadByte(uint16_t bAdd)
// See PIC18F46Q71 data sheet, section 10.4.1, Example 10-9
{
    // Set NVMADR with the target word address: 0x380000 - 0x3800FF
    // See data sheet Figure 9-1 Program and Data Memory Map
    NVMADRU = 0x38;
    NVMADRH = (uint8_t)((bAdd & 0xFF00) >> 8);
    NVMADRL = (uint8_t)(bAdd & 0x00FF);
    //
    // Start DATAEE read
    NVMCON1bits.CMD = 0b000;
    NVMCON0bits.GO = 1;
    while (NVMCON0bits.GO) /* wait */ ;
    //
    return (NVMDATL);
}
